version: '3.2'

networks:
  integration-test-assessment:

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    container_name: it-tests
    volumes:
      - $PWD:/go/src/target
    depends_on:
      - db_test
    networks:
      - integration-test-assessment
  db_test:
    image: postgres:15.1-alpine
    container_name: test-assessment-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test-assessment-db
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test-assessment
